[jumphost]
jump ansible_host=127.0.0.1 ansible_port=2222 ansible_user=aleksei

[nexus]
vm20 ansible_host=10.10.0.20 ansible_user=aleksei ansible_ssh_common_args='-o ProxyJump=jump'

[nexus]
vm20 ansible_host=10.10.0.20 ansible_user=aleksei ansible_ssh_common_args='-o ProxyJump=jump'


[vms]
vm10 ansible_host=10.10.0.10 ansible_user=aleksei ansible_ssh_common_args='-o ProxyJump=jump'
vm11 ansible_host=10.10.0.11 ansible_user=aleksei ansible_ssh_common_args='-o ProxyJump=jump'
vm20 ansible_host=10.10.0.20 ansible_user=aleksei ansible_ssh_common_args='-o ProxyJump=jump'

[vms:vars]
ansible_python_interpreter=/usr/bin/python3


